### ISSUE TITLE
Cmd::run does not respect overrident stdin contents

### ISSUE THREAD

**Issue by MikailBag** [matklad/xshell#13]
https://github.com/matklad/xshell/blob/master/src/lib.rs#L395

`run` simply creates an std Command with correct args and executes it. Stdin bytes set with `Cmd::stdin` do not take effect, and stdin is still inherited.

**Comment by azdavis** [comment]
Seems like stdin redirection works:

- https://github.com/matklad/xshell/blob/c543794bb0487d6f14ceca61f866dbab40f1d35b/src/lib.rs#L1013-L1019
- https://github.com/matklad/xshell/blob/11ab785e5a78b1c35eadceca35848dac6a494843/tests/it/main.rs#L213-L240

If it's not working for your case, please open a new issue with a specific example that doesn't work. Thanks!
