### ISSUE TITLE
Single quotes prevent interpolation

### ISSUE THREAD

**Issue by ngirard** [matklad/xshell#4]
```rust
let pwd = env::var("PWD").unwrap();
cmd!("echo 'Hello from {pwd}'").run()?;
```
produces
```sh
Hello from {pwd}
```

instead of the expected
```sh
Hello from /home/ngirard/....
```

**Comment by matklad** [comment]
I wouldn't say that this is an explicitly designed behavior, but I think it is reasonable. The shell works that way, there's no interpolation in single quotes. 

```
let pwd = env::var("PWD").unwrap();
cmd!("echo 'Hello from '{pwd}").run()?;
```

will do what you want

**Comment by ngirard** [comment]
Well, I'm not sure it's the most readable & comfortable option...

Let's take another example: `notify-send` expects the string to be displayed to be given as a single argument.
What would then be the equivalent Xshell `cmd!` statement to the following shell command ?
```sh
notify-send "Hello from $PWD"
```

**Comment by matklad** [comment]
`cmd!(“notify-send 'Hello from '{PWD}“)`

Adjacent tokens are concated into a single arg. But I do agree that this is kinda silly. I think I need to bite the bullet and implement proper escapensequences and double quoted strings, so that your example just works.

**Comment by ngirard** [comment]
I think that would be a valuable improvement.

Thanks in advance !

**Comment by azzamsa** [comment]
> The shell works that way, there's no interpolation in single quotes

So it is okay to close this issue.
