### ISSUE TITLE
`ignore_status` should take a boolean argument

### ISSUE THREAD

**Issue by matklad** [matklad/xshell#41]
We should spell it as `.ignore_status(true)`, to match `.echo_cmd()` and in general to be a friendlier API. Sadly, that would be a breaking change.

**Comment by azdavis** [comment]
We do have `set_ignore_status`: https://github.com/matklad/xshell/blob/11ab785e5a78b1c35eadceca35848dac6a494843/src/lib.rs#L877-L880
