### ISSUE TITLE
`set_*` on `Cmd` should return `Self` and not take it by reference

### ISSUE THREAD

**Issue by repnop** [matklad/xshell#59]
The rest of the builder-style options do this, but not the `set_*`, which is a really awkward divide when you want to have those be configurable from elsewhere.

**Comment by matklad** [comment]
That's intentional: `set_` work even if you have only `&mut Cmd`. The other methods take `self` to make the following work: 

```rust
let mut cmd = xshell::cmd!().quiet();
cmd.run()
```

Perhaps we should add `with_` family though?
